### ISSUE TITLE
consider using json functions for links and forks

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-sqlite-indexer#4]
right now we turn the links and forks arrays into strings to store them in sqlite. we could instead use json in sql: https://www.sqlite.org/json1.html

**Comment by gmaclennan** [comment]
yes I came here to say this same thing. I learnt about sqlite json functions after writing this, and when I first wrote the json extension was not included by default in sqlite (it is now). I think this is a worthwhile change to make before we come out of alpha.

**Comment by gmaclennan** [comment]
Resolved in 945a8edea0d52de41427e4e73c4f937847ec2fef

SQLite doesn't actually have anything special for writing JSON: this commit just stringifies the forks and version arrays as JSON rather than comma-delimited strings. This is slightly safer (can have a comma in a version ID) and does allow us to use the SQL JSON functions to query the data, if we need to, which could be useful in the future. I think worth making this breaking change now (previous index tables will need re-created, since we change the column types to non-nullable).
